### ISSUE TITLE
Generated QR code in demo overflows the display width

### ISSUE THREAD

**Issue by lvlingxiao1** [Samarium150/qr.ts#13]
this can be fixed by 3 lines of css:
```css
canvas {
    max-width: 100%;
}
```
